<link rel="stylesheet" href="/css/materia/light_box/index.css">
<link rel="stylesheet" href="/css/materia/light_box/carrousel.css">
<link rel="stylesheet" href="/css/materia/light_box/arrows.css">
<link rel="stylesheet" href="/css/materias/lateral_menu.css">
<link rel="stylesheet" href="/css/materias/circle_btn.css">
<link rel="stylesheet" href="/css/materia/index.css">
<link rel="stylesheet" href="/css/materia/acordion/index.css">
<link rel="stylesheet" href="/css/materia/acordion/section_btns.css">
<link rel="stylesheet" href="/css/materia/acordion/community.css">
<link rel="stylesheet" href="/css/materia/quizz.css">
<link rel="stylesheet" href="/css/base/front_page.css"> 
<link rel="stylesheet" href="/css/base/thumbnails.css">